name: Swift-teste

on:
  push:
    branches: [ master ]
 

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.3,name=iPhone 11', 'platform=tvOS Simulator,OS=13.3,name=Apple TV 4K']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and test
        run: |
          cd MovieDB_SwiftUI
          xcodebuild clean test -project MovieDB_SwiftUI.xcodeproj -scheme MovieDB_SwiftUI -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
