name: Swift-teste

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
  
  codev:
    runs-on: macos-latest
    steps:       
      - name: Codecov
      - uses: codecov/codecov-action@v1.0.6
