name: Swift-teste

on:
  push:
    branches: [ master ]
 

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.3,name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and test
        run: |
          ls
          xcodebuild clean test -project MovieDB_SwiftUI.xcodeproj -scheme MovieDB_SwiftUI -destination "${destination}" CODE_SIGN_IDENTITY="2c286aae-a457-4b82-b1c3-33d9c4d79981" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
