name: Swift-teste

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
  
  codev:
    steps: 
      - name: Codecov
        runs-on: macos-latest
        uses: codecov/codecov-action@v1.0.6
