name: Swift-teste

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  codev:
    runs-on: macos-latest
    steps:       
      - name: Codecov
        uses: codecov/codecov-action@v1.0.6
          language:
            - swift
          osx_image: xcode10.1
          script:
            - xcodebuild -scheme SwiftExample -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=12.1' build test
          after_success:
            - bash <(curl -s https://codecov.io/bash)
